os:
  # TODO: Add OSX
  - linux
compiler:
  - clang
  - gcc
language: cpp
dist: xenial
before_install:
  - mkdir deps && cd deps
  - wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.4.0%2Bcpu.zip
  - unzip libtorch-cxx11-abi-shared-with-deps-1.4.0+cpu.zip
  - cd ..
#  - sudo apt-get update
#  - sudo apt-get install python3-dev python3-pip
#  - sudo pip3 install --upgrade pip &> /dev/null
#  - USE_CUDA=0 pip3 install --user torch==1.4.0 --no-binary=torch --progress-bar off
script:
  - USE_CUDA=0 mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$(realpath ../deps/libtorch) .. && make
#  - - USE_CUDA=0 mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$(../scripts/libtorch-root) .. && make
  - ctest -VV
