os:
  # TODO: Add OSX
  - linux
compiler:
  - clang
  - gcc
python:
  - "3.7"
language: cpp
dist: bionic
before_install:
#  - sudo apt-get update
#  - sudo apt-get install python3-dev python3-pip
  - pyenv global system 3.7.6
  - USE_CUDA=0 pip3.7 install --user numpy torch==1.4.0 --progress-bar off
script:
  - pip list
  - python3.7 -c 'import torch; print(torch.__file__)'
  - scripts/libtorch-root
#  - USE_CUDA=0 mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$(python3.7 ../scripts/libtorch-root) .. && make
  - USE_CUDA=0 mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=/home/travis/.local/lib/python3.7/site-packages/torch/ .. && make
  - ctest -VV
