os:
  # TODO: Add OSX
  - linux
compiler:
  - clang
  - gcc
python:
  - "3.6"
language: cpp
dist: xenial
before_install:
#  - sudo apt-get update
#  - sudo apt-get install python3-dev python3-pip
  - USE_CUDA=0 pip install --user torch==1.4.0 --progress-bar off
script:
  - USE_CUDA=0 mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$(../scripts/libtorch-root) .. && make
  - ctest -VV
