os:
  - linux
  - osx
compiler:
  - clang
  - gcc
language: cpp
dist: xenial
before_install:
  - sudo apt-get update
  - sudo apt-get install python3-dev python3-pip
  - pip3 install --progress-bar off --user torch==1.4.0
script:
  - mkdir build && cd build && cmake -DCMAKE_PREFIX_PATH=$(../scripts/libtorch-root) .. && make
  - ctest -VV
